services:
  image_watcher:
    build: .
    image: image-processor:latest
    container_name: image-watcher
    restart: always
    network_mode: "bridge"  # Uses the existing default bridge
    environment:
      WHITE_THRESHOLD: 230
      BLACK_THRESHOLD: 150
      SLEEP_BEFORE_PROCESS: 1.0
      WATCH_FOLDER: "/watch"
      COMPLETED_FOLDER: "/completed"
      ORIGINALS_FOLDER: "/processed_originals"
    volumes:
      - ./watch:/watch
      - ./completed:/completed
      - ./processed_originals:/processed_originals
    command: ["python", "auto_transparent.py"]

  image_web:
    image: image-processor:latest
    container_name: image-web
    restart: always
    network_mode: "bridge"  # Uses the existing default bridge
    ports:
      - "5000:5000"
    environment:
      WHITE_THRESHOLD: 230
      BLACK_THRESHOLD: 150
      WATCH_FOLDER: "/watch"
      COMPLETED_FOLDER: "/completed"
      ORIGINALS_FOLDER: "/processed_originals"
    volumes:
      - ./watch:/watch
      - ./completed:/completed
      - ./processed_originals:/processed_originals
    command: ["python", "web_app.py"]
    depends_on:
      - image_watcher
